# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from reswarm_msgs_matlab/ReswarmCasadiStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class ReswarmCasadiStatus(genpy.Message):
  _md5sum = "c10c75bfe58d45337011894405a5c1a0"
  _type = "reswarm_msgs_matlab/ReswarmCasadiStatus"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """time stamp
bool coord_ok
bool mrpi_finished
bool traj_finished
string control_mode

"""
  __slots__ = ['stamp','coord_ok','mrpi_finished','traj_finished','control_mode']
  _slot_types = ['time','bool','bool','bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,coord_ok,mrpi_finished,traj_finished,control_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ReswarmCasadiStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.coord_ok is None:
        self.coord_ok = False
      if self.mrpi_finished is None:
        self.mrpi_finished = False
      if self.traj_finished is None:
        self.traj_finished = False
      if self.control_mode is None:
        self.control_mode = ''
    else:
      self.stamp = genpy.Time()
      self.coord_ok = False
      self.mrpi_finished = False
      self.traj_finished = False
      self.control_mode = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I3B().pack(_x.stamp.secs, _x.stamp.nsecs, _x.coord_ok, _x.mrpi_finished, _x.traj_finished))
      _x = self.control_mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 11
      (_x.stamp.secs, _x.stamp.nsecs, _x.coord_ok, _x.mrpi_finished, _x.traj_finished,) = _get_struct_2I3B().unpack(str[start:end])
      self.coord_ok = bool(self.coord_ok)
      self.mrpi_finished = bool(self.mrpi_finished)
      self.traj_finished = bool(self.traj_finished)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.control_mode = str[start:end].decode('utf-8')
      else:
        self.control_mode = str[start:end]
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I3B().pack(_x.stamp.secs, _x.stamp.nsecs, _x.coord_ok, _x.mrpi_finished, _x.traj_finished))
      _x = self.control_mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 11
      (_x.stamp.secs, _x.stamp.nsecs, _x.coord_ok, _x.mrpi_finished, _x.traj_finished,) = _get_struct_2I3B().unpack(str[start:end])
      self.coord_ok = bool(self.coord_ok)
      self.mrpi_finished = bool(self.mrpi_finished)
      self.traj_finished = bool(self.traj_finished)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.control_mode = str[start:end].decode('utf-8')
      else:
        self.control_mode = str[start:end]
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I3B = None
def _get_struct_2I3B():
    global _struct_2I3B
    if _struct_2I3B is None:
        _struct_2I3B = struct.Struct("<2I3B")
    return _struct_2I3B
