// Generated by gencpp from file reswarm_msgs/ReswarmPlannerStatus.msg
// DO NOT EDIT!


#ifndef RESWARM_MSGS_MESSAGE_RESWARMPLANNERSTATUS_H
#define RESWARM_MSGS_MESSAGE_RESWARMPLANNERSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reswarm_msgs
{
template <class ContainerAllocator>
struct ReswarmPlannerStatus_
{
  typedef ReswarmPlannerStatus_<ContainerAllocator> Type;

  ReswarmPlannerStatus_()
    : stamp()
    , planner_finished(false)
    , sent_robustMPC(false)
    , sent_PID(false)  {
    }
  ReswarmPlannerStatus_(const ContainerAllocator& _alloc)
    : stamp()
    , planner_finished(false)
    , sent_robustMPC(false)
    , sent_PID(false)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef uint8_t _planner_finished_type;
  _planner_finished_type planner_finished;

   typedef uint8_t _sent_robustMPC_type;
  _sent_robustMPC_type sent_robustMPC;

   typedef uint8_t _sent_PID_type;
  _sent_PID_type sent_PID;





  typedef boost::shared_ptr< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ReswarmPlannerStatus_

typedef ::reswarm_msgs::ReswarmPlannerStatus_<std::allocator<void> > ReswarmPlannerStatus;

typedef boost::shared_ptr< ::reswarm_msgs::ReswarmPlannerStatus > ReswarmPlannerStatusPtr;
typedef boost::shared_ptr< ::reswarm_msgs::ReswarmPlannerStatus const> ReswarmPlannerStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reswarm_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/usr/local/MATLAB/R2021a/sys/ros1/glnxa64/ros1/share/geometry_msgs/cmake/../msg'], 'reswarm_msgs': ['/home/albee/workspaces/astrobee-ws-reswarm/freeflyer-reswarm/develop/reswarm_msgs/reswarm_msgs_matlab/matlab_msg_gen_ros1/glnxa64/src/reswarm_msgs/msg'], 'std_msgs': ['/usr/local/MATLAB/R2021a/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg', '/usr/local/MATLAB/R2021a/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937ba029a6f652c8475e7e4b90e4b7d4";
  }

  static const char* value(const ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937ba029a6f652c8ULL;
  static const uint64_t static_value2 = 0x475e7e4b90e4b7d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reswarm_msgs/ReswarmPlannerStatus";
  }

  static const char* value(const ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"bool planner_finished\n"
"bool sent_robustMPC\n"
"bool sent_PID\n"
"\n"
;
  }

  static const char* value(const ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.planner_finished);
      stream.next(m.sent_robustMPC);
      stream.next(m.sent_PID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReswarmPlannerStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reswarm_msgs::ReswarmPlannerStatus_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "planner_finished: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.planner_finished);
    s << indent << "sent_robustMPC: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sent_robustMPC);
    s << indent << "sent_PID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sent_PID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RESWARM_MSGS_MESSAGE_RESWARMPLANNERSTATUS_H
