
classdef ReswarmSrvMRPIRequest < ros.Message
    %ReswarmSrvMRPIRequest MATLAB implementation of reswarm_msgs/ReswarmSrvMRPIRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'reswarm_msgs/ReswarmSrvMRPIRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '56a0e756ddda6756b17b0fc7891e1cfa' % The MD5 Checksum of the message definition
        PropertyList = { 'W' 'UMax' 'Dt' 'Mass' 'QPosAnc' 'QVelAnc' 'RAnc' } % List of non-constant message properties
        ROSPropertyList = { 'w' 'u_max' 'dt' 'mass' 'Q_pos_anc' 'Q_vel_anc' 'R_anc' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Float64MultiArray' ...
            'ros.msggen.std_msgs.Float64MultiArray' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        W
        UMax
        Dt
        Mass
        QPosAnc
        QVelAnc
        RAnc
    end
    methods
        function set.W(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Float64MultiArray'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmSrvMRPIRequest', 'W')
            obj.W = val;
        end
        function set.UMax(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Float64MultiArray'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmSrvMRPIRequest', 'UMax')
            obj.UMax = val;
        end
        function set.Dt(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmSrvMRPIRequest', 'Dt');
            obj.Dt = double(val);
        end
        function set.Mass(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmSrvMRPIRequest', 'Mass');
            obj.Mass = double(val);
        end
        function set.QPosAnc(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmSrvMRPIRequest', 'QPosAnc');
            obj.QPosAnc = double(val);
        end
        function set.QVelAnc(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmSrvMRPIRequest', 'QVelAnc');
            obj.QVelAnc = double(val);
        end
        function set.RAnc(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmSrvMRPIRequest', 'RAnc');
            obj.RAnc = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.reswarm_msgs.ReswarmSrvMRPIRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.reswarm_msgs.ReswarmSrvMRPIRequest(strObj);
        end
    end
end
