
classdef ReswarmPlannerStatus < ros.Message
    %ReswarmPlannerStatus MATLAB implementation of reswarm_msgs/ReswarmPlannerStatus
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'reswarm_msgs/ReswarmPlannerStatus' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '937ba029a6f652c8475e7e4b90e4b7d4' % The MD5 Checksum of the message definition
        PropertyList = { 'Stamp' 'PlannerFinished' 'SentRobustMPC' 'SentPID' } % List of non-constant message properties
        ROSPropertyList = { 'stamp' 'planner_finished' 'sent_robustMPC' 'sent_PID' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msg.Time' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Stamp
        PlannerFinished
        SentRobustMPC
        SentPID
    end
    methods
        function set.Stamp(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.Time'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmPlannerStatus', 'Stamp')
            obj.Stamp = val;
        end
        function set.PlannerFinished(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmPlannerStatus', 'PlannerFinished');
            obj.PlannerFinished = logical(val);
        end
        function set.SentRobustMPC(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmPlannerStatus', 'SentRobustMPC');
            obj.SentRobustMPC = logical(val);
        end
        function set.SentPID(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmPlannerStatus', 'SentPID');
            obj.SentPID = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.reswarm_msgs.ReswarmPlannerStatus.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.reswarm_msgs.ReswarmPlannerStatus(strObj);
        end
    end
end
