
classdef ReswarmUCBoundStatus < ros.Message
    %ReswarmUCBoundStatus MATLAB implementation of reswarm_msgs/ReswarmUCBoundStatus
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'reswarm_msgs/ReswarmUCBoundStatus' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2b2edd0b612536cbf5dddb2726f0dffa' % The MD5 Checksum of the message definition
        PropertyList = { 'Stamp' 'UcBoundFinished' 'UnitTestComplete' } % List of non-constant message properties
        ROSPropertyList = { 'stamp' 'uc_bound_finished' 'unit_test_complete' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msg.Time' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Stamp
        UcBoundFinished
        UnitTestComplete
    end
    methods
        function set.Stamp(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.Time'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmUCBoundStatus', 'Stamp')
            obj.Stamp = val;
        end
        function set.UcBoundFinished(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmUCBoundStatus', 'UcBoundFinished');
            obj.UcBoundFinished = logical(val);
        end
        function set.UnitTestComplete(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmUCBoundStatus', 'UnitTestComplete');
            obj.UnitTestComplete = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.reswarm_msgs.ReswarmUCBoundStatus.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.reswarm_msgs.ReswarmUCBoundStatus(strObj);
        end
    end
end
