# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from reswarm_msgs/ReswarmPlannerStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class ReswarmPlannerStatus(genpy.Message):
  _md5sum = "937ba029a6f652c8475e7e4b90e4b7d4"
  _type = "reswarm_msgs/ReswarmPlannerStatus"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """time stamp
bool planner_finished
bool sent_robustMPC
bool sent_PID

"""
  __slots__ = ['stamp','planner_finished','sent_robustMPC','sent_PID']
  _slot_types = ['time','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,planner_finished,sent_robustMPC,sent_PID

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ReswarmPlannerStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.planner_finished is None:
        self.planner_finished = False
      if self.sent_robustMPC is None:
        self.sent_robustMPC = False
      if self.sent_PID is None:
        self.sent_PID = False
    else:
      self.stamp = genpy.Time()
      self.planner_finished = False
      self.sent_robustMPC = False
      self.sent_PID = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I3B().pack(_x.stamp.secs, _x.stamp.nsecs, _x.planner_finished, _x.sent_robustMPC, _x.sent_PID))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 11
      (_x.stamp.secs, _x.stamp.nsecs, _x.planner_finished, _x.sent_robustMPC, _x.sent_PID,) = _get_struct_2I3B().unpack(str[start:end])
      self.planner_finished = bool(self.planner_finished)
      self.sent_robustMPC = bool(self.sent_robustMPC)
      self.sent_PID = bool(self.sent_PID)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I3B().pack(_x.stamp.secs, _x.stamp.nsecs, _x.planner_finished, _x.sent_robustMPC, _x.sent_PID))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 11
      (_x.stamp.secs, _x.stamp.nsecs, _x.planner_finished, _x.sent_robustMPC, _x.sent_PID,) = _get_struct_2I3B().unpack(str[start:end])
      self.planner_finished = bool(self.planner_finished)
      self.sent_robustMPC = bool(self.sent_robustMPC)
      self.sent_PID = bool(self.sent_PID)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I3B = None
def _get_struct_2I3B():
    global _struct_2I3B
    if _struct_2I3B is None:
        _struct_2I3B = struct.Struct("<2I3B")
    return _struct_2I3B
