# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from reswarm_msgs/ReswarmStatusSecondary.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class ReswarmStatusSecondary(genpy.Message):
  _md5sum = "758d13e0328708709b74b234c19edbd1"
  _type = "reswarm_msgs/ReswarmStatusSecondary"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """time stamp

# Config Info
# base (shared) values
int32 test_number
bool default_control
string flight_mode
bool test_finished
bool coord_ok

# SecondaryStatus
# DMPC Status Flags
int32 solver_status
float32 cost_value
float32 kkt_value
float32 sol_time
"""
  __slots__ = ['stamp','test_number','default_control','flight_mode','test_finished','coord_ok','solver_status','cost_value','kkt_value','sol_time']
  _slot_types = ['time','int32','bool','string','bool','bool','int32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,test_number,default_control,flight_mode,test_finished,coord_ok,solver_status,cost_value,kkt_value,sol_time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ReswarmStatusSecondary, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.test_number is None:
        self.test_number = 0
      if self.default_control is None:
        self.default_control = False
      if self.flight_mode is None:
        self.flight_mode = ''
      if self.test_finished is None:
        self.test_finished = False
      if self.coord_ok is None:
        self.coord_ok = False
      if self.solver_status is None:
        self.solver_status = 0
      if self.cost_value is None:
        self.cost_value = 0.
      if self.kkt_value is None:
        self.kkt_value = 0.
      if self.sol_time is None:
        self.sol_time = 0.
    else:
      self.stamp = genpy.Time()
      self.test_number = 0
      self.default_control = False
      self.flight_mode = ''
      self.test_finished = False
      self.coord_ok = False
      self.solver_status = 0
      self.cost_value = 0.
      self.kkt_value = 0.
      self.sol_time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2IiB().pack(_x.stamp.secs, _x.stamp.nsecs, _x.test_number, _x.default_control))
      _x = self.flight_mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2Bi3f().pack(_x.test_finished, _x.coord_ok, _x.solver_status, _x.cost_value, _x.kkt_value, _x.sol_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.stamp.secs, _x.stamp.nsecs, _x.test_number, _x.default_control,) = _get_struct_2IiB().unpack(str[start:end])
      self.default_control = bool(self.default_control)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.flight_mode = str[start:end].decode('utf-8')
      else:
        self.flight_mode = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.test_finished, _x.coord_ok, _x.solver_status, _x.cost_value, _x.kkt_value, _x.sol_time,) = _get_struct_2Bi3f().unpack(str[start:end])
      self.test_finished = bool(self.test_finished)
      self.coord_ok = bool(self.coord_ok)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2IiB().pack(_x.stamp.secs, _x.stamp.nsecs, _x.test_number, _x.default_control))
      _x = self.flight_mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2Bi3f().pack(_x.test_finished, _x.coord_ok, _x.solver_status, _x.cost_value, _x.kkt_value, _x.sol_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.stamp.secs, _x.stamp.nsecs, _x.test_number, _x.default_control,) = _get_struct_2IiB().unpack(str[start:end])
      self.default_control = bool(self.default_control)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.flight_mode = str[start:end].decode('utf-8')
      else:
        self.flight_mode = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.test_finished, _x.coord_ok, _x.solver_status, _x.cost_value, _x.kkt_value, _x.sol_time,) = _get_struct_2Bi3f().unpack(str[start:end])
      self.test_finished = bool(self.test_finished)
      self.coord_ok = bool(self.coord_ok)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2IiB = None
def _get_struct_2IiB():
    global _struct_2IiB
    if _struct_2IiB is None:
        _struct_2IiB = struct.Struct("<2IiB")
    return _struct_2IiB
_struct_2Bi3f = None
def _get_struct_2Bi3f():
    global _struct_2Bi3f
    if _struct_2Bi3f is None:
        _struct_2Bi3f = struct.Struct("<2Bi3f")
    return _struct_2Bi3f
