
classdef ReswarmTestNumber < ros.Message
    %ReswarmTestNumber MATLAB implementation of reswarm_msgs_matlab/ReswarmTestNumber
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'reswarm_msgs_matlab/ReswarmTestNumber' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'a546cf58ee360e93604091100205de8f' % The MD5 Checksum of the message definition
        PropertyList = { 'Stamp' 'TestNumber' 'Role' } % List of non-constant message properties
        ROSPropertyList = { 'stamp' 'test_number' 'role' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msg.Time' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Stamp
        TestNumber
        Role
    end
    methods
        function set.Stamp(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.Time'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmTestNumber', 'Stamp')
            obj.Stamp = val;
        end
        function set.TestNumber(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmTestNumber', 'TestNumber');
            obj.TestNumber = int32(val);
        end
        function set.Role(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'ReswarmTestNumber', 'Role');
            obj.Role = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.reswarm_msgs_matlab.ReswarmTestNumber.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.reswarm_msgs_matlab.ReswarmTestNumber(strObj);
        end
    end
end
