
classdef ReswarmInfoStatus < ros.Message
    %ReswarmInfoStatus MATLAB implementation of reswarm_msgs_matlab/ReswarmInfoStatus
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'reswarm_msgs_matlab/ReswarmInfoStatus' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'a26bd2c93c5e901d9b6c26d2a732da2c' % The MD5 Checksum of the message definition
        PropertyList = { 'Stamp' 'InfoTrajSent' } % List of non-constant message properties
        ROSPropertyList = { 'stamp' 'info_traj_sent' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msg.Time' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Stamp
        InfoTrajSent
    end
    methods
        function set.Stamp(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.Time'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmInfoStatus', 'Stamp')
            obj.Stamp = val;
        end
        function set.InfoTrajSent(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmInfoStatus', 'InfoTrajSent');
            obj.InfoTrajSent = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.reswarm_msgs_matlab.ReswarmInfoStatus.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.reswarm_msgs_matlab.ReswarmInfoStatus(strObj);
        end
    end
end
