
classdef ReswarmCasadiStatus < ros.Message
    %ReswarmCasadiStatus MATLAB implementation of reswarm_msgs_matlab/ReswarmCasadiStatus
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'reswarm_msgs_matlab/ReswarmCasadiStatus' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'c10c75bfe58d45337011894405a5c1a0' % The MD5 Checksum of the message definition
        PropertyList = { 'Stamp' 'CoordOk' 'MrpiFinished' 'TrajFinished' 'ControlMode' } % List of non-constant message properties
        ROSPropertyList = { 'stamp' 'coord_ok' 'mrpi_finished' 'traj_finished' 'control_mode' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msg.Time' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Stamp
        CoordOk
        MrpiFinished
        TrajFinished
        ControlMode
    end
    methods
        function set.Stamp(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.Time'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmCasadiStatus', 'Stamp')
            obj.Stamp = val;
        end
        function set.CoordOk(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmCasadiStatus', 'CoordOk');
            obj.CoordOk = logical(val);
        end
        function set.MrpiFinished(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmCasadiStatus', 'MrpiFinished');
            obj.MrpiFinished = logical(val);
        end
        function set.TrajFinished(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ReswarmCasadiStatus', 'TrajFinished');
            obj.TrajFinished = logical(val);
        end
        function set.ControlMode(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'ReswarmCasadiStatus', 'ControlMode');
            obj.ControlMode = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.reswarm_msgs_matlab.ReswarmCasadiStatus.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.reswarm_msgs_matlab.ReswarmCasadiStatus(strObj);
        end
    end
end
