// Generated by gencpp from file reswarm_msgs_matlab/ReswarmSrvMRPIRequest.msg
// DO NOT EDIT!


#ifndef RESWARM_MSGS_MATLAB_MESSAGE_RESWARMSRVMRPIREQUEST_H
#define RESWARM_MSGS_MATLAB_MESSAGE_RESWARMSRVMRPIREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64MultiArray.h>
#include <std_msgs/Float64MultiArray.h>

namespace reswarm_msgs_matlab
{
template <class ContainerAllocator>
struct ReswarmSrvMRPIRequest_
{
  typedef ReswarmSrvMRPIRequest_<ContainerAllocator> Type;

  ReswarmSrvMRPIRequest_()
    : w()
    , u_max()
    , dt(0.0)
    , mass(0.0)
    , Q_pos_anc(0.0)
    , Q_vel_anc(0.0)
    , R_anc(0.0)  {
    }
  ReswarmSrvMRPIRequest_(const ContainerAllocator& _alloc)
    : w(_alloc)
    , u_max(_alloc)
    , dt(0.0)
    , mass(0.0)
    , Q_pos_anc(0.0)
    , Q_vel_anc(0.0)
    , R_anc(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _w_type;
  _w_type w;

   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _u_max_type;
  _u_max_type u_max;

   typedef double _dt_type;
  _dt_type dt;

   typedef double _mass_type;
  _mass_type mass;

   typedef double _Q_pos_anc_type;
  _Q_pos_anc_type Q_pos_anc;

   typedef double _Q_vel_anc_type;
  _Q_vel_anc_type Q_vel_anc;

   typedef double _R_anc_type;
  _R_anc_type R_anc;





  typedef boost::shared_ptr< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReswarmSrvMRPIRequest_

typedef ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<std::allocator<void> > ReswarmSrvMRPIRequest;

typedef boost::shared_ptr< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest > ReswarmSrvMRPIRequestPtr;
typedef boost::shared_ptr< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest const> ReswarmSrvMRPIRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reswarm_msgs_matlab

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/usr/local/MATLAB/R2021a/sys/ros1/glnxa64/ros1/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/usr/local/MATLAB/R2021a/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg', '/usr/local/MATLAB/R2021a/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg'], 'reswarm_msgs_matlab': ['/home/albee/workspaces/astrobee-ws-reswarm/freeflyer-reswarm/develop/reswarm_msgs/reswarm_msgs_matlab/matlab_msg_gen_ros1/glnxa64/src/reswarm_msgs_matlab/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56a0e756ddda6756b17b0fc7891e1cfa";
  }

  static const char* value(const ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56a0e756ddda6756ULL;
  static const uint64_t static_value2 = 0xb17b0fc7891e1cfaULL;
};

template<class ContainerAllocator>
struct DataType< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reswarm_msgs_matlab/ReswarmSrvMRPIRequest";
  }

  static const char* value(const ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64MultiArray w\n"
"std_msgs/Float64MultiArray u_max\n"
"float64 dt\n"
"float64 mass\n"
"float64 Q_pos_anc\n"
"float64 Q_vel_anc\n"
"float64 R_anc\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float64[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.w);
      stream.next(m.u_max);
      stream.next(m.dt);
      stream.next(m.mass);
      stream.next(m.Q_pos_anc);
      stream.next(m.Q_vel_anc);
      stream.next(m.R_anc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReswarmSrvMRPIRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reswarm_msgs_matlab::ReswarmSrvMRPIRequest_<ContainerAllocator>& v)
  {
    s << indent << "w: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.w);
    s << indent << "u_max: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.u_max);
    s << indent << "dt: ";
    Printer<double>::stream(s, indent + "  ", v.dt);
    s << indent << "mass: ";
    Printer<double>::stream(s, indent + "  ", v.mass);
    s << indent << "Q_pos_anc: ";
    Printer<double>::stream(s, indent + "  ", v.Q_pos_anc);
    s << indent << "Q_vel_anc: ";
    Printer<double>::stream(s, indent + "  ", v.Q_vel_anc);
    s << indent << "R_anc: ";
    Printer<double>::stream(s, indent + "  ", v.R_anc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RESWARM_MSGS_MATLAB_MESSAGE_RESWARMSRVMRPIREQUEST_H
